### PR TITLE
ZFS 2.1.2

### PR DESCRIPTION
**Pull request by jackpot51**
Improves compatibility with newer kernels (#2)

### CODE REVIEW

**Comment by jacobgkau** [comment]
It looks like this failed to build on everything but 22.04. Trying to build locally on 21.10, it wants a newer version of `abigail-tools` than what's available.

**Comment by jackpot51** [comment]
I still haven't solved the issues, this will likely need a backport of libabigail 2.0 to 20.04 and 21.10

**Comment by jackpot51** [comment]
Updated libabigail in https://github.com/pop-os/libabigail. I will revert the last commit when it builds.

**Comment by jackpot51** [comment]
It is ready on Pop. It will be ready on Ubuntu once libabigail shows up on the staging repos there

**Comment by jackpot51** [comment]
This is ready for review now, built on 20.04 and 21.10 Pop and Ubuntu

**Review by jacobgkau — APPROVED** [review]
Able to create/import and mount pools:

OS | Kernel 5.15.23 | Kernel 5.16.11
-----|-----------------|-----------------
Pop!_OS 21.10 | [X] | [X]
Pop!_OS 20.04 LTS | [X] | [X]
Ubuntu 20.04 LTS | [X] | [X]

**Pull request merged**
